In [1]:
import xpress as xp
import pandas as pd
import numpy as np

In [2]:
import pandas as pd
movie_database = pd.read_csv("movie_database.csv", encoding='ISO-8859-1')
movie_database.head()

,title,vote_average,vote_count,release_date,revenue,runtime,budget,popularity,genres,n_ad_breaks,runtime_with_ads,scaled_popularity,children_scaled_popularity,adults_scaled_popularity,retirees_scaled_popularity,license fee
0,Inception,8.364,34495,2010/7/15,825532764,148,160000000,83.952,"['Action', 'Science Fiction', 'Adventure']",5,180,0.972027,0.777622,0.972027,0.388811,1155532.76
1,Interstellar,8.417,32571,2014/11/5,701729206,169,165000000,140.241,"['Adventure', 'Drama', 'Science Fiction']",6,210,1.000000,0.600000,1.000000,0.600000,1041729.21
2,The Dark Knight,8.512,30619,2008/7/16,1004558444,152,185000000,130.643,"['Drama', 'Action', 'Crime', 'Thriller']",6,180,1.000000,0.600000,1.000000,0.800000,1384558.44
3,Avatar,7.573,29815,2009/12/15,2923706026,162,237000000,79.932,"['Action', 'Adventure', 'Fantasy', 'Science Fi...",6,180,0.958199,0.766559,0.958199,0.383280,3407706.03
4,The Avengers,7.710,29166,2012/4/25,1518815515,143,220000000,98.082,"['Science Fiction', 'Action', 'Adventure']",5,180,1.000000,0.800000,1.000000,0.400000,1968815.52

In [3]:
channel0 = pd.read_excel("max_channel_0_conversion_rates.xlsx")
channel0.head()

,time slot,Western,Adventure,Crime,Thriller,Fantasy,Documentary,Music,Action,TV Movie,...,Mystery,Science Fiction,Comedy,Family,Horror,War,Animation,History,Romance,Maximum Conversion rate
0,2024-10-01 07:05:00,0.0,0.0,0.0,0.1750,0.0,0.0,0.0,0.0,0.0,...,0.1750,0.0,0.000000,0.0,0.1750,0.0,0.0,0.0,0.000000,0.175000
1,2024-10-01 07:35:00,0.0,0.0,0.0,0.0875,0.0,0.0,0.0,0.0,0.0,...,0.0875,0.0,0.123744,0.0,0.0875,0.0,0.0,0.0,0.123744,0.123744
2,2024-10-01 08:10:00,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,...,0.0000,0.0,0.247487,0.0,0.0000,0.0,0.0,0.0,0.247487,0.247487
3,2024-10-01 08:40:00,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,...,0.0000,0.0,0.247487,0.0,0.0000,0.0,0.0,0.0,0.247487,0.247487
4,2024-10-01 09:10:00,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,...,0.0000,0.0,0.247487,0.0,0.0000,0.0,0.0,0.0,0.247487,0.247487

In [4]:
channel = pd.read_excel("NewchannelA.xlsx")
channel.head()

,timeslot,children_baseline_view_count,adults_baseline_view_count,retirees_baseline_view_count,prime_time_factor
0,07:00:00,0.019383,0.022296,0.003611,1.0
1,07:30:00,0.015485,0.022928,0.004694,1.0
2,08:00:00,0.009684,0.024245,0.006021,1.0
3,08:30:00,0.004744,0.026238,0.007612,1.0
4,09:00:00,0.001831,0.028892,0.009478,1.0

In [5]:
channel1 = pd.read_excel("Max_channel_1_conversion_rates.xlsx")
channel1.head()

,Unnamed: 0,Western,Adventure,Crime,Thriller,Fantasy,Documentary,Music,Action,TV Movie,...,Mystery,Science Fiction,Comedy,Family,Horror,War,Animation,History,Romance,Maximum
0,2024-10-01 07:05:00,0.0,0.0,0.202073,0.0,0.0,0.0,0.0,0.0,0.0,...,0.202073,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.202073
1,2024-10-01 07:35:00,0.0,0.0,0.101036,0.0,0.0,0.0,0.0,0.0,0.0,...,0.101036,0.0,0.123744,0.0,0.0,0.0,0.0,0.0,0.0,0.224780
2,2024-10-01 08:10:00,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.247487,0.0,0.0,0.0,0.0,0.0,0.0,0.247487
3,2024-10-01 08:40:00,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.247487,0.0,0.0,0.0,0.0,0.0,0.0,0.247487
4,2024-10-01 09:10:00,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.247487,0.0,0.0,0.0,0.0,0.0,0.0,0.247487

In [6]:
channel2 = pd.read_excel("Max_channel_2_conversion_rates.xlsx")
channel2.head()

,Unnamed: 0,Western,Adventure,Crime,Thriller,Fantasy,Documentary,Music,Action,TV Movie,...,Mystery,Science Fiction,Comedy,Family,Horror,War,Animation,History,Romance,Maximum
0,2024-10-01 07:05:00,0.0,0.156525,0.000000,0.0,0.0,0.0,0.0,0.000000,0,...,0.0,0.0,0.156525,0.156525,0.0,0.0,0.156525,0.0,0.0,0.156525
1,2024-10-01 07:35:00,0.0,0.156525,0.000000,0.0,0.0,0.0,0.0,0.000000,0,...,0.0,0.0,0.156525,0.156525,0.0,0.0,0.156525,0.0,0.0,0.156525
2,2024-10-01 08:05:00,0.0,0.156525,0.000000,0.0,0.0,0.0,0.0,0.000000,0,...,0.0,0.0,0.156525,0.156525,0.0,0.0,0.156525,0.0,0.0,0.156525
3,2024-10-01 08:35:00,0.0,0.078262,0.101036,0.0,0.0,0.0,0.0,0.101036,0,...,0.0,0.0,0.078262,0.078262,0.0,0.0,0.078262,0.0,0.0,0.179299
4,2024-10-01 09:10:00,0.0,0.000000,0.202073,0.0,0.0,0.0,0.0,0.202073,0,...,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.202073

In [7]:
channel_sch_0=pd.read_csv("channel_0_schedule.csv",encoding='ISO-8859-1')
channel_sch_0.head()

,Unnamed: 0,content,content_type,movie_popularity_factor,children_popularity_factor,adults_popularity_factor,retirees_popularity_factor,movie_budget,box_office_revenue,n_ad_breaks,...,retirees_true_view_count_1,retirees_true_view_count_2,retirees_true_view_count_3,retirees_true_view_count_4,retirees_true_view_count_5,retirees_true_view_count_6,retirees_true_view_count_7,retirees_true_view_count_8,retirees_true_view_count_9,ad_slot_price
0,2024-10-01 07:00:00,The Skeleton Key,Movie,0.439117,0.175647,0.439117,0.351294,43000000.0,93983911.0,4.0,...,0.002154,0.000000,0.000000,0.002392,0.000302,0.000000,0.000000,0.000561,0.001560,NaN
1,2024-10-01 07:05:00,Advert,Advert,0.439117,0.175647,0.439117,0.351294,43000000.0,93983911.0,4.0,...,0.003195,0.001218,0.001775,0.000000,0.000000,0.000418,0.000655,0.000943,0.000084,56995.17
2,2024-10-01 07:10:00,The Skeleton Key,Movie,0.439117,0.175647,0.439117,0.351294,43000000.0,93983911.0,4.0,...,0.000000,0.000536,0.002948,0.002226,0.000000,0.000000,0.001026,0.000004,0.001667,NaN
3,2024-10-01 07:15:00,The Skeleton Key,Movie,0.439117,0.175647,0.439117,0.351294,43000000.0,93983911.0,4.0,...,0.002499,0.002200,0.000371,0.000000,0.000000,0.000000,0.001487,0.003326,0.000000,NaN
4,2024-10-01 07:20:00,The Skeleton Key,Movie,0.439117,0.175647,0.439117,0.351294,43000000.0,93983911.0,4.0,...,0.000412,0.002303,0.001661,0.000650,0.000759,0.004024,0.000600,0.000000,0.000541,NaN

In [8]:
channel_sch_1=pd.read_excel("channel_1_schedule.xlsx")
channel_sch_1.head()

,Unnamed: 0,content,content_type,movie_popularity_factor,children_popularity_factor,adults_popularity_factor,retirees_popularity_factor,movie_budget,box_office_revenue,n_ad_breaks,...,retirees_true_view_count_1,retirees_true_view_count_2,retirees_true_view_count_3,retirees_true_view_count_4,retirees_true_view_count_5,retirees_true_view_count_6,retirees_true_view_count_7,retirees_true_view_count_8,retirees_true_view_count_9,ad_slot_price
0,2024-10-01 07:00:00,Cop Land,Movie,0.448213,0.179285,0.448213,0.448213,15000000,44862187,4,...,0.000000,0.004481,0.001593,0.000000,0.006112,0.001909,0.000000,0.003265,0.002688,NaN
1,2024-10-01 07:05:00,Advert,Advert,0.448213,0.179285,0.448213,0.448213,15000000,44862187,4,...,0.000000,0.003439,0.002406,0.008659,0.002627,0.002673,0.004126,0.004219,0.003107,25458.66
2,2024-10-01 07:10:00,Cop Land,Movie,0.448213,0.179285,0.448213,0.448213,15000000,44862187,4,...,0.006375,0.000714,0.004579,0.006266,0.000000,0.005424,0.002833,0.000000,0.005875,NaN
3,2024-10-01 07:15:00,Cop Land,Movie,0.448213,0.179285,0.448213,0.448213,15000000,44862187,4,...,0.003335,0.004368,0.005206,0.003004,0.001120,0.000000,0.003981,0.004050,0.005560,NaN
4,2024-10-01 07:20:00,Cop Land,Movie,0.448213,0.179285,0.448213,0.448213,15000000,44862187,4,...,0.000000,0.004008,0.000000,0.000000,0.003358,0.006782,0.002327,0.000532,0.000709,NaN

In [9]:
channel_sch_2=pd.read_csv("channel_2_schedule.csv")
channel_sch_2.head()

,Unnamed: 0,content,content_type,movie_popularity_factor,children_popularity_factor,adults_popularity_factor,retirees_popularity_factor,movie_budget,box_office_revenue,n_ad_breaks,...,retirees_true_view_count_1,retirees_true_view_count_2,retirees_true_view_count_3,retirees_true_view_count_4,retirees_true_view_count_5,retirees_true_view_count_6,retirees_true_view_count_7,retirees_true_view_count_8,retirees_true_view_count_9,ad_slot_price
0,2024-10-01 07:00:00,Inside Out,Movie,1.0,0.8,0.8,0.8,175000000.0,857611174.0,4.0,...,0.005147,0.000046,0.001079,0.004945,0.003570,0.006120,0.005488,0.007212,0.000000,NaN
1,2024-10-01 07:05:00,Advert,Advert,1.0,0.8,0.8,0.8,175000000.0,857611174.0,4.0,...,0.001236,0.000000,0.005220,0.007198,0.001363,0.007132,0.004534,0.007934,0.008600,365283.35
2,2024-10-01 07:10:00,Inside Out,Movie,1.0,0.8,0.8,0.8,175000000.0,857611174.0,4.0,...,0.002607,0.002485,0.001190,0.003209,0.004286,0.006725,0.004420,0.004781,0.002691,NaN
3,2024-10-01 07:15:00,Inside Out,Movie,1.0,0.8,0.8,0.8,175000000.0,857611174.0,4.0,...,0.004725,0.000353,0.005734,0.012065,0.002319,0.001463,0.006641,0.006233,0.003693,NaN
4,2024-10-01 07:20:00,Inside Out,Movie,1.0,0.8,0.8,0.8,175000000.0,857611174.0,4.0,...,0.001454,0.006480,0.008878,0.000630,0.000000,0.004220,0.002365,0.003027,0.001067,NaN

In [10]:
df_0=pd.DataFrame(channel0)  
C = channel0['time slot'].unique().tolist()  # 示例：从数据集中提取所有唯一类别
maximum_coversion=df_0["Maximum Conversion rate"].tolist()

In [11]:
df_1=pd.DataFrame(channel1)
C = channel1['Unnamed: 0'].unique().tolist()  # 示例：从数据集中提取所有唯一类别
maximum_coversion1=df_1['Maximum'].tolist()

In [12]:
df_2=pd.DataFrame(channel2)
C = channel2['Unnamed: 0'].unique().tolist()  # 示例：从数据集中提取所有唯一类别
maximum_coversion2=df_2['Maximum'].tolist()

In [13]:
df_sch_1=pd.DataFrame(channel_sch_1)

In [14]:
df_sch_0=pd.DataFrame(channel_sch_0)

In [15]:
df_sch_2=pd.DataFrame(channel_sch_2)

In [16]:
import pandas as pd

# 假设你有一个DataFrame
data =pd.read_csv("channel_0_schedule.csv")

channel_sch_0 = pd.DataFrame(data)
# 确保列是字符串类型
#channel_sch_0['ad_slot_price'] = channel_sch_0['ad_slot_price'].astype(str)
df_sch_0 = channel_sch_0.fillna(0)

#print(df_sch_0)
ad_t_list = [[],[],[]]
for i in range(len(channel_sch_0)):
    if channel_sch_0.loc[i,'content_type']=='Advert':
        ad_t_list[0].append(i)
#print(ad_t_list)



# 输出筛选后的DataFrame
#print(df_clean_0)
# 保存结果到 Excel 文件
#df_clean_0.to_excel('D:/mmcs data/ads withtimaslot.xlsx', index=False)

In [17]:
import pandas as pd

# 假设你有一个DataFrame
data =pd.read_excel("channel_1_schedule.xlsx")

channel_sch_1 = pd.DataFrame(data)
# 确保列是字符串类型
#channel_sch_1['ad_slot_price'] = channel_sch_1['ad_slot_price'].astype(str)
# 筛选掉包含'NaN'字眼的行
#df_clean_1 = channel_sch_1[~channel_sch_1['ad_slot_price'].str.contains('nan', na=False)]
df_sch_1 = channel_sch_1.fillna(0)

#print(df_sch_1)

for i in range(len(channel_sch_1)):
    if channel_sch_1.loc[i,'content_type']=='Advert':
        ad_t_list[1].append(i)
#print(ad_t_list)


# 输出筛选后的DataFrame
#print(df_clean_1)

In [18]:
import pandas as pd

# 假设你有一个DataFrame
data =pd.read_csv("channel_2_schedule.csv")

channel_sch_2 = pd.DataFrame(data)
# 确保列是字符串类型
#channel_sch_2['ad_slot_price'] = channel_sch_2['ad_slot_price'].astype(str)
# 筛选掉包含'NaN'字眼的行
#df_clean_2 = channel_sch_2[~channel_sch_2['ad_slot_price'].str.contains('nan', na=False)]
#NaN transfers to 0
df_sch_2 = channel_sch_2.fillna(0)

print(df_sch_2)

for i in range(len(channel_sch_2)):
    if channel_sch_2.loc[i,'content_type']=='Advert':
        ad_t_list[2].append(i)
print(ad_t_list)


# 输出筛选后的DataFrame
#print(df_clean_2)

                Unnamed: 0                content content_type  \
0      2024-10-01 07:00:00             Inside Out        Movie
1      2024-10-01 07:05:00                 Advert       Advert
2      2024-10-01 07:10:00             Inside Out        Movie
3      2024-10-01 07:15:00             Inside Out        Movie
4      2024-10-01 07:20:00             Inside Out        Movie
...                    ...                    ...          ...
17131  2024-12-23 23:35:00  The French Connection        Movie
17132  2024-12-23 23:40:00  The French Connection        Movie
17133  2024-12-23 23:45:00  The French Connection        Movie
17134  2024-12-23 23:50:00                 Advert       Advert
17135  2024-12-23 23:55:00             Enemy Mine        Movie

       movie_popularity_factor  children_popularity_factor  \
0                     1.000000                    0.800000
1                     1.000000                    0.800000
2                     1.000000                    0.800000
3                     1.000000                    0.800000
4                     1.000000                    0.800000
...                        ...                         ...
17131                 0.383943                    0.230366
17132                 0.383943                    0.230366
17133                 0.383943                    0.230366
17134                 0.383943                    0.230366
17135                 0.434972                    0.173989

       adults_popularity_factor  retirees_popularity_factor  movie_budget  \
0                      0.800000                    0.800000   175000000.0
1                      0.800000                    0.800000   175000000.0
2                      0.800000                    0.800000   175000000.0
3                      0.800000                    0.800000   175000000.0
4                      0.800000                    0.800000   175000000.0
...                         ...                         ...           ...
17131                  0.383943                    0.230366     1800000.0
17132                  0.383943                    0.230366     1800000.0
17133                  0.383943                    0.230366     1800000.0
17134                  0.383943                    0.230366     1800000.0
17135                  0.434972                    0.347978    40000000.0

       box_office_revenue  n_ad_breaks  ...  retirees_true_view_count_1  \
0             857611174.0          4.0  ...                    0.005147
1             857611174.0          4.0  ...                    0.001236
2             857611174.0          4.0  ...                    0.002607
3             857611174.0          4.0  ...                    0.004725
4             857611174.0          4.0  ...                    0.001454
...                   ...          ...  ...                         ...
17131          41158757.0          4.0  ...                    0.000491
17132          41158757.0          4.0  ...                    0.000677
17133          41158757.0          4.0  ...                    0.008484
17134          41158757.0          4.0  ...                    0.002316
17135          12303411.0          4.0  ...                    0.000034

       retirees_true_view_count_2  retirees_true_view_count_3  \
0                        0.000046                    0.001079
1                        0.000000                    0.005220
2                        0.002485                    0.001190
3                        0.000353                    0.005734
4                        0.006480                    0.008878
...                           ...                         ...
17131                    0.000968                    0.004436
17132                    0.002435                    0.002441
17133                    0.006791                    0.004336
17134                    0.008864                    0.002832
17135                    0.002415                    0.004392

       retirees_true_view_count_4  retirees_true_view_count_5  \
0                        0.004945                    0.003570
1                        0.007198                    0.001363
2                        0.003209                    0.004286
3                        0.012065                    0.002319
4                        0.000630                    0.000000
...                           ...                         ...
17131                    0.004363                    0.003183
17132                    0.003851                    0.000000
17133                    0.000000                    0.001368
17134                    0.000000                    0.000029
17135                    0.001770                    0.007522

       retirees_true_view_count_6  retirees_true_view_count_7  \
0                        0.006120                    0.005488
1                        0.007132                    0.004534
2                        0.006725                    0.004420
3                        0.001463                    0.006641
4                        0.004220                    0.002365
...                           ...                         ...
17131                    0.003330                    0.006105
17132                    0.007966                    0.001001
17133                    0.002242                    0.001728
17134                    0.000000                    0.002283
17135                    0.000026                    0.005807

       retirees_true_view_count_8  retirees_true_view_count_9  ad_slot_price
0                        0.007212                    0.000000           0.00
1                        0.007934                    0.008600      365283.35
2                        0.004781                    0.002691           0.00
3                        0.006233                    0.003693           0.00
4                        0.003027                    0.001067           0.00
...                           ...                         ...            ...
17131                    0.005126                    0.002025           0.00
17132                    0.004120                    0.000000           0.00
17133                    0.000162                    0.000000           0.00
17134                    0.004264                    0.000392       16427.63
17135                    0.002125                    0.002178           0.00

[17136 rows x 48 columns]

In [19]:


df = pd.DataFrame(channel)


T = (df.index+1).tolist()

children_baseline = df['children_baseline_view_count'].tolist()
adults_baseline = df['adults_baseline_view_count'].tolist()
retirees_baseline = df['retirees_baseline_view_count'].tolist()

In [20]:

movies_df = pd.DataFrame(movie_database)

# Extract relevant parameters
M = (movies_df.index+1).tolist()  # Movie IDs

pc = movies_df['children_scaled_popularity'].tolist()  # Popularity of children for each movie
pa = movies_df['adults_scaled_popularity'].tolist()    # Popularity of adults for each movie
pr = movies_df['retirees_scaled_popularity'].tolist()  # Popularity of retirees for each movie
# Runtime with ads
d = movies_df['runtime_with_ads'].tolist()  # Runtime for each movie

In [21]:
# 11.23 get array of movie genres
df_mg=pd.DataFrame(movie_database)  
genre = df_mg['genres']
mg_list = np.zeros((5920,19))
genre_list = ['Western','Adventure','Crime','Thriller','Fantasy','Documentary','Music','Action','TV Movie','Drama','Mystery','Science Fiction','Comedy','Family','Horror','War','Animation',\
              'History','Romance']
for i in range(5920):
    for j in range(19):
        if genre_list[j] in genre[i]:
            mg_list[i,j]=1

In [22]:
# 11.23 get array of ads genres in channel 0
slot_num = 68
adg_list = np.zeros((3,slot_num,19))
df_adg0=pd.DataFrame(channel0)  
for i in range(slot_num):
    for j in range(19):
        if df_adg0.iloc[i,j+1]>0:
            adg_list[0,i,j]=1

In [23]:
# 11.23 get array of ads genres in channel 2
df_adg2=pd.DataFrame(channel2)  
for i in range(slot_num):
    for j in range(19):
        if df_adg2.iloc[i,j+1]>0:
            adg_list[2,i,j]=1

In [24]:
# 11.23 get array of ads genres in channel 1
df_adg1=pd.DataFrame(channel1)  
for i in range(slot_num):
    for j in range(19):
        if df_adg1.iloc[i,j+1]>0:
            adg_list[1,i,j]=1

In [25]:
# Check if there are NaN or inf values in any of the parameters
import numpy as np

# Check for NaN or inf in the baseline arrays
print("NaN or inf in children_baseline:", np.any(np.isnan(children_baseline)), np.any(np.isinf(children_baseline)))
print("NaN or inf in adults_baseline:", np.any(np.isnan(adults_baseline)), np.any(np.isinf(adults_baseline)))
print("NaN or inf in retirees_baseline:", np.any(np.isnan(retirees_baseline)), np.any(np.isinf(retirees_baseline)))

# Check if there are NaN or inf in the movie parameters
print("NaN or inf in pc:", np.any(np.isnan(pc)), np.any(np.isinf(pc)))
print("NaN or inf in pa:", np.any(np.isnan(pa)), np.any(np.isinf(pa)))
print("NaN or inf in pr:", np.any(np.isnan(pr)), np.any(np.isinf(pr)))


# Replace NaN or inf values with 0 in the parameters
pc = np.nan_to_num(pc, nan=0, posinf=0, neginf=0)
pa = np.nan_to_num(pa, nan=0, posinf=0, neginf=0)
pr = np.nan_to_num(pr, nan=0, posinf=0, neginf=0)
children_baseline = np.nan_to_num(children_baseline, nan=0, posinf=0, neginf=0)
adults_baseline = np.nan_to_num(adults_baseline, nan=0, posinf=0, neginf=0)
retirees_baseline = np.nan_to_num(retirees_baseline, nan=0, posinf=0, neginf=0)

NaN or inf in children_baseline: False False
NaN or inf in adults_baseline: False False
NaN or inf in retirees_baseline: False False
NaN or inf in pc: False False
NaN or inf in pa: False False
NaN or inf in pr: False False

In [26]:
xp.init('C:/xpressmp/bin/xpauth.xpr')

In [27]:
# C=[1,2,3]
# T={1:[1,2,3],2:[1,2],3:[1,2,3,4]}
# for c in C:
#     for t in T[c]:
#         print(t)

# T_ad = {0:list(range(63)),1:list(range(63)),2:list(range(62))}
# print(T_ad[0])
# T = list(range(63))
# print(T)

In [28]:
num_time_slots = 34*1
num_movies = 100
max_time = 700 # time in seconds
num_channels=3
num_genre = 19

T = list(range(num_time_slots))  # example of T (you can adjust the size)
M = list(range(num_movies))  # example of M (you can adjust the size)
T1 = list(range(33,num_time_slots-1,34)) # 11.19
T_ad = {0:list(range(63)),1:list(range(63)),2:list(range(62))}
C = list(range(num_channels))  
G = list(range(num_channels))
prob = xp.problem(name='myproblem')
#xp.init('/Applications/FICO Xpress/xpressmp/bin/xpauth.xpr')
#xp.init('C:/xpressmp/bin/xpauth.xpr')
#variables
x = {(movie_database.loc[m,'title'], t): xp.var(vartype=xp.binary, name='x_{0}_{1}'.format(movie_database.loc[m,'title'], t))
     for t in T for m in M}
y = {movie_database.loc[m,'title']: xp.var(vartype=xp.binary, name='y_{0}'.format(movie_database.loc[m,'title'])) for m in M}
s = {movie_database.loc[m,'title']: xp.var(vartype=xp.continuous, name='s_{0}'.format(movie_database.loc[m,'title'])) for m in M}
e = {movie_database.loc[m,'title']: xp.var(vartype=xp.continuous, name='e_{0}'.format(movie_database.loc[m,'title'])) for m in M}
N = 1000000
z = {(m, c, t): xp.var(vartype=xp.binary, name=f'z_{m}_{c}_{t}')for m in M for c in C for t in T_ad[c]}
# 11.23  flag to mark whether at least one movie genre is same as ads genre
f = {(movie_database.loc[m, 'title'], t, c, g): xp.var(vartype=xp.binary, name='f_{0}_{1}_{2}_{3}'.format(movie_database.loc[m, 'title'], t, c, g)) 
    for c in C for t in T_ad[c] for m in M for g in G}

#z = {(movie_database.loc[m, 'title'], t, c): xp.var(vartype=xp.binary, name='x_{0}_{1}_{2}'.format(movie_database.loc[m, 'title'], t, c)) 
#     for c in C for t in T for m in M}

prob.addVariable(x,y,s,e,z)

channal_0_time_slots = [32, 63, 95, 127, 160, 192, 225]
channal_1_time_slots = [33, 63, 94, 125, 157, 187, 219]
channal_2_time_slots = [32, 62, 94, 126, 159, 191, 223]
T2 = list(range(channal_0_time_slots[6]))
T3 = list(range(channal_1_time_slots[6]))
T4 = list(range(channal_2_time_slots[6]))
n=2
#constraint
# assum ads budget
#total_budget = xp.Sum(ad_slot_price_0.loc[c, 'ad_slot_price'] + ad_slot_price_1.loc[c, 'ad_slot_price'] + ad_slot_price_2.loc[c, 'ad_slot_price'] * z[(c, m, t)]
#                      for c in C for m in M for t in T)
#ad_movie= [xp.Sum(z[movie_database.loc[m,'title'],c,t] for m in M for t in T for c in C) <= y[movie_database.loc[m,'title']]]
#ad_min_in_day = [t * z[movie_database.loc[m, 'title'], c, t] <= s[movie_database.loc[m, 'title']] * 30
#    for m in M for t in T for c in C]


by_day = [x[movie_database.loc[m,'title'], t] <= 1 - x[movie_database.loc[m,'title'], t+1] for t in T1 for m in M] # 11.19
assignment = [xp.Sum(x[movie_database.loc[m,'title'], t] for m in M) == 1 for t in T]
full_duration = [xp.Sum(x[movie_database.loc[m,'title'], t] for t in T) ==y[movie_database.loc[m,'title']]*movie_database.loc[m,'runtime_with_ads']/30 for m in M]
start_time = [s[movie_database.loc[m,'title']] <= t*x[movie_database.loc[m,'title'], t] + (1-x[movie_database.loc[m,'title'], t])*num_time_slots for t in T for m in M]
end_time = [e[movie_database.loc[m,'title']] >= (t+1)*x[movie_database.loc[m,'title'], t]  for t in T for m in M]
run_time = [e[movie_database.loc[m,'title']] - s[movie_database.loc[m,'title']] == y[movie_database.loc[m,'title']]*movie_database.loc[m,'runtime_with_ads']/30 for m in M]
advert_const = [xp.Sum(z.get((movie_database.loc[m, 'title'], c, t), 0) for m in M) <= 1 for c in C for t in T_ad[c]]
# only show ads if our channel stream the movie
# if the ads genre is the same as the movie
#advert_const4= [y[movie_database.loc[m,'title']]*mg_list[m,g] >= f[(movie_database.loc[m,'title'], t,c,g)] for c in C for t in T_ad[c] for m in M for g in G]
#advert_const5 = [
 # z.get((movie_database.loc[m, 'title'], c, t), 0) * adg_list[c, t, g] >= f.get((movie_database.loc[m, 'title'], t, c, g), 0)
 # for c in C for t in T_ad[c] for m in M for g in G]
#advert_const6= [xp.Sum(f[(movie_database.loc[m,'title'], t,c,g)] for g in G) >= z.get((movie_database.loc[m,'title'], c, t), 0) for c in C for t in T_ad[c] for m in M]

# advertise constraint   11.23
# ads show before movie
advert_const2 = [5 * ad_t_list[c][t] * z.get((movie_database.loc[m,'title'], c, t), 0) <= 30 * s[movie_database.loc[m,'title']] 
                 for m in M for c in C for t in T_ad[c]] 

# only show ads if our channel stream the movie
advert_const3 = [
    xp.Sum(z.get((movie_database.loc[m,'title'], c, t), 0) for c in C for t in T_ad[c]) 
    <= num_time_slots * xp.Sum(x[movie_database.loc[m,'title'], t] for t in T)
    for m in M
]

prob.addConstraint(assignment,full_duration,start_time,end_time,run_time,by_day,advert_const2,advert_const,advert_const3)#,advert_const6)

#objective function
weighted_view_count =xp.Sum(x[movie_database.loc[m, 'title'], t] * (
      df.loc[t, 'children_baseline_view_count'] * movie_database.loc[m, 'children_scaled_popularity'] + 
       df.loc[t, 'adults_baseline_view_count'] * movie_database.loc[m, 'adults_scaled_popularity'] + 
      df.loc[t, 'retirees_baseline_view_count'] * movie_database.loc[m, 'retirees_scaled_popularity']
   )  for t in T for m in M)* N

weighted_conversion_rate_count =xp.Sum(
    (
        xp.Sum((df_0.loc[t, 'Maximum Conversion rate'] * df_sch_0.loc[t, 'children_true_view_count_1'] +
         df_0.loc[t, 'Maximum Conversion rate'] * df_sch_0.loc[t, 'adults_true_view_count_1'] +
         df_0.loc[t, 'Maximum Conversion rate'] * df_sch_0.loc[t, 'retirees_true_view_count_1']) * z[(m, 0, t)] for t in T_ad[0])+
        xp.Sum((df_1.loc[t, 'Maximum'] * df_sch_1.loc[t, 'children_true_view_count_1'] +
         df_1.loc[t, 'Maximum'] * df_sch_1.loc[t, 'adults_true_view_count_1'] +
         df_1.loc[t, 'Maximum'] * df_sch_1.loc[t, 'retirees_true_view_count_1']) * z[(m, 1, t)] for t in T_ad[1])+
        xp.Sum((df_2.loc[t, 'Maximum'] * df_sch_2.loc[t, 'children_true_view_count_1'] +
         df_2.loc[t, 'Maximum'] * df_sch_2.loc[t, 'adults_true_view_count_1'] +
         df_2.loc[t, 'Maximum'] * df_sch_2.loc[t, 'retirees_true_view_count_1']) * z[(m, 2, t)] for t in T_ad[2])
    ) * N for m in M)

#Minimize advertsing cost=total budget
objective = weighted_view_count + weighted_conversion_rate_count
#objective2= objective2= xp.Sum(movie_database.loc[m,'license fee']*y[movie_database.loc[m,'title']]+xp.Sum(
# df_sch_0.loc[c,'ad_slot_price'] for t in T2[channal_0_time_slots[n-2]:channal_1_time_slots[n-1]]+df_sch_1.loc[c,'ad_slot_price'] for t in T3[channal_1_time_slots[n-2]:channal_1_time_slots[n-1]]
#    +df_sch_2.loc[c,'ad_slot_price'] for t in T4[channal_2_time_slots[n-2]:channal_2_time_slots[n-1]])*z[(c, m, t)] for c in C for m in M)
# objective2 = xp.Sum(
#     movie_database.loc[m, 'license fee'] * y[movie_database.loc[m, 'title']] + 
#     xp.Sum(
#         df_sch_0.loc[t, 'ad_slot_price']*z[(0, m, t)] for t in T
#    ) + 
#     xp.Sum(
#         df_sch_1.loc[t, 'ad_slot_price']*z[(1, m, t)] for t in T
#     ) +
#     xp.Sum(
#         df_sch_2.loc[t, 'ad_slot_price']*z[(2, m, t)] for t in T
#     )for m in M)

objective2 = xp.Sum(
    movie_database.loc[m, 'license fee'] * y[movie_database.loc[m, 'title']] + 
    xp.Sum(
        df_sch_0.loc[t, 'ad_slot_price']*z[(m, 0, t)] for t in T2[channal_0_time_slots[n-2]:channal_0_time_slots[n-1]]
   ) + 
    xp.Sum(
        df_sch_1.loc[t, 'ad_slot_price']*z[(m, 1, t)] for t in T3[channal_1_time_slots[n-2]:channal_1_time_slots[n-1]]
    ) +
    xp.Sum(
        df_sch_2.loc[t, 'ad_slot_price']*z[(m, 2, t)] for t in T4[channal_2_time_slots[n-2]:channal_2_time_slots[n-1]]
    )for m in M)
# Combine both objective functions into a single objective (example: you want to minimize objective2 and maximize objective)
combined_objective = 0.9*objective - 0.1*objective2  # Or you can scale them if you need a balance between them

# Set the objective function to maximize the combined objective
prob.setObjective(objective, sense=xp.maximize)  # Or xp.maximize if you prefer to minimize the result

In [29]:
prob.setControl('maxtime', max_time )
print(prob.getControl('maxtime'))
best_bound = prob.getAttrib('bestbound')
mip_gap = 100*((prob.getObjVal()-best_bound)/prob.getObjVal())

700

In [30]:
xp.setOutputEnabled(True)
prob.solve()

FICO Xpress v9.4.2, Hyper, solve started 23:46:00, Feb 27, 2025
Heap usage: 11MB (peak 11MB, 472KB system)
Maximizing MILP myproblem using up to 12 threads and up to 15GB memory, with these control settings:
MAXTIME = 700
OUTPUTLOG = 1
NLPPOSTSOLVE = 1
XSLP_DELETIONCONTROL = 0
XSLP_OBJSENSE = -1
Original problem has:
     26122 rows        22500 cols        43000 elements     22300 entities
Presolved problem has:
      6933 rows         3598 cols        20398 elements      3398 entities
LP relaxation tightened
Presolve finished in 0 seconds
Heap usage: 16MB (peak 29MB, 472KB system)

Coefficient range                    original                 solved
  Coefficients   [min,max] : [ 1.00e+00,  3.40e+01] / [ 3.13e-02,  1.94e+00]
  RHS and bounds [min,max] : [ 1.00e+00,  3.40e+01] / [ 1.00e+00,  3.40e+01]
  Objective      [min,max] : [ 3.48e+02,  1.71e+05] / [ 1.46e+04,  1.71e+05]
Autoscaling applied standard scaling

Symmetric problem: generators: 10, support set: 476
 Number of orbits: 144, largest orbit: 6
 Row orbits: 276, row support: 966
Will try to keep branch and bound tree memory usage below 7.9GB
 *** Solution found:  126858039.4   Time:   0.14    Heuristic: i ***
Starting concurrent solve with dual (1 thread) and barrier (11 threads)

              Concurrent-Solve,   0s
            Dual                      Barrier
    objective   sum inf
 P  1.275E+08   .0000000 |
                         |
------- optimal -------- | ----- interrupted ------
Concurrent statistics:
           Dual: 244 simplex iterations, 0.00s
        Barrier: 0 barrier and 0 simplex iterations, 0.01s
            Barrier used 11 threads 6 cores
            Barrier used AVX2 support
Optimal solution found

   Its         Obj Value      S   Ninf  Nneg        Sum Inf  Time
   244       127464758.3      P      0     0        .000000     0
Dual solved problem
  244 simplex iterations in 0.01 seconds at time 0

Final objective                       : 1.274647583222556e+08
  Max primal violation      (abs/rel) :       0.0 /       0.0
  Max dual violation        (abs/rel) : 1.455e-11 / 1.370e-11
  Max complementarity viol. (abs/rel) :       0.0 /       0.0

Starting root cutting & heuristics
Deterministic mode with up to 1 additional thread

 Its Type    BestSoln    BestBound   Sols    Add    Del     Gap     GInf   Time
R         127089698.4  127464370.4      2                  0.29%       0      0
R         127420115.5  127464370.4      3                  0.03%       0      0
R         127431712.6  127464370.4      4                  0.03%       0      0
R         127447430.3  127464370.4      5                  0.01%       0      0
   1  K   127447430.3  127464370.4      5    290      0    0.01%      59      0

Cuts in the matrix         : 290
Cut elements in the matrix : 17040

Performing root presolve...

Reduced problem has:    3093 rows    1484 columns     11232 elements
Presolve dropped   :    4130 rows    2114 columns     26206 elements
Presolve tightened :       759 elements
Symmetric problem: generators: 9, support set: 368
 Number of orbits: 98, largest orbit: 6
 Row orbits: 187, row support: 748
Will try to keep branch and bound tree memory usage below 7.8GB
Crash basis containing 77 structural columns created

   Its         Obj Value      S   Ninf  Nneg        Sum Inf  Time
  1013       127464473.7      P      0     0        .000000     0
Optimal solution found
Dual solved problem
  1013 simplex iterations in 0.00 seconds at time 0

Final objective                       : 1.274644737230774e+08
  Max primal violation      (abs/rel) :       0.0 /       0.0
  Max dual violation        (abs/rel) : 5.768e-12 / 3.296e-12
  Max complementarity viol. (abs/rel) :       0.0 /       0.0

Starting root cutting & heuristics
Deterministic mode with up to 1 additional thread

 Its Type    BestSoln    BestBound   Sols    Add    Del     Gap     GInf   Time
   1  K   127447430.3  127464181.0      5    152    258    0.01%      30      0
   2  K   127447430.3  127464098.8      5    227    155    0.01%      32      0
   3  K   127447430.3  127463968.1      5    161    214    0.01%      28      0
   4  K   127447430.3  127462349.2      5    323    158    0.01%      74      0
   5  K   127447430.3  127462316.6      5     42    312    0.01%      37      0
   6  K   127447430.3  127461841.1      5    319     50    0.01%      74      0
   7  K   127447430.3  127460952.1      5    284    310    0.01%      69      0
   8  K   127447430.3  127460848.0      5    347    286    0.01%      76      0
   9  K   127447430.3  127460442.5      5    518    347    0.01%      82      0

Cuts in the matrix         : 572
Cut elements in the matrix : 4387

Performing root presolve...

Reduced problem has:    1952 rows     737 columns      8042 elements
Presolve dropped   :    1424 rows     747 columns      4583 elements
Presolve tightened :       580 elements
Symmetric problem: generators: 9, support set: 260
 Number of orbits: 71, largest orbit: 6
 Row orbits: 133, row support: 532
Will try to keep branch and bound tree memory usage below 7.8GB
Crash basis containing 41 structural columns created

   Its         Obj Value      S   Ninf  Nneg        Sum Inf  Time
  2826       127462834.2      P      0     0        .000000     0
Optimal solution found
Dual solved problem
  2826 simplex iterations in 0.00 seconds at time 0

Final objective                       : 1.274628342285784e+08
  Max primal violation      (abs/rel) :       0.0 /       0.0
  Max dual violation        (abs/rel) : 6.920e-12 / 6.920e-12
  Max complementarity viol. (abs/rel) :       0.0 /       0.0
STOPPING - MIPRELSTOP target reached (MIPRELSTOP=0.0001  gap=9.99361e-05).
 *** Search completed ***
Uncrunching matrix
Final MIP objective                   : 1.274474302754840e+08
Final MIP bound                       : 1.274601681434446e+08
  Solution time / primaldual integral :      0.74s/ 28.818211%
  Number of solutions found / nodes   :         5 /         0
  Max primal violation      (abs/rel) : 1.887e-15 / 4.441e-16
  Max integer violation     (abs    ) : 4.441e-16

(<SolveStatus.COMPLETED: 3>, <SolStatus.OPTIMAL: 1>)

In [31]:
prob.write("problem","lp")

In [32]:
x_sol = {(movie_database.loc[m,'title'], t): prob.getSolution(x[movie_database.loc[m,'title'], t]) for t in T for m in M if prob.getSolution(x[movie_database.loc[m,'title'], t]) > 0.001}
s_sol = {movie_database.loc[m,'title']: prob.getSolution(s[movie_database.loc[m,'title']]) for m in M}

s_sol1 = xp.Sum({movie_database.loc[m,'title']: prob.getSolution(df.loc[t, 'children_baseline_view_count'] * movie_database.loc[m, 'children_scaled_popularity'])*N for t in T for m in M})
s_sol2 = xp.Sum({movie_database.loc[m,'title']: prob.getSolution(df.loc[t, 'adults_baseline_view_count'] * movie_database.loc[m, 'adults_scaled_popularity'])*N for t in T for m in M})
s_sol3 = xp.Sum({movie_database.loc[m,'title']: prob.getSolution(df.loc[t, 'retirees_baseline_view_count'] * movie_database.loc[m, 'retirees_scaled_popularity'])*N for t in T for m in M})

print(f"children viewership: {s_sol1}")
print(f"adult viewership: {s_sol2}")
print(f"retirees viewership: {s_sol3}")

children viewership: 8356.69
adult viewership: 7.06177e+06
retirees viewership: 319470

In [33]:
import pandas as pd

# 假设 prob.getSolution() 返回了决策变量的值
# 例如，这里假设 s_sol1, s_sol2, s_sol3 是 xpress 表达式，可以通过 prob.getSolution() 获取求解的值。

# 创建一个字典来存储每个 (movie, time_slot) 的结果
s_sol1_dict = {}
s_sol2_dict = {}
s_sol3_dict = {}

# 假设 T 是时间槽的集合，M 是电影的集合
for t in T:
    for m in M:
        # 获取 s_sol1, s_sol2, s_sol3 对应的结果
        s_sol1_dict[(movie_database.loc[m, 'title'], t)] = prob.getSolution(df.loc[t, 'children_baseline_view_count'] * movie_database.loc[m, 'children_scaled_popularity']) * N
        s_sol2_dict[(movie_database.loc[m, 'title'], t)] = prob.getSolution(df.loc[t, 'adults_baseline_view_count'] * movie_database.loc[m, 'adults_scaled_popularity']) * N
        s_sol3_dict[(movie_database.loc[m, 'title'], t)] = prob.getSolution(df.loc[t, 'retirees_baseline_view_count'] * movie_database.loc[m, 'retirees_scaled_popularity']) * N

# 将字典转换为 DataFrame 格式
data1 = [(movie, time_slot, value) for (movie, time_slot), value in s_sol1_dict.items()]
data2 = [(movie, time_slot, value) for (movie, time_slot), value in s_sol2_dict.items()]
data3 = [(movie, time_slot, value) for (movie, time_slot), value in s_sol3_dict.items()]

# 创建 DataFrame
df_s_sol1 = pd.DataFrame(data1, columns=['Movie', 'Time Slot', 'Children Viewership'])
df_s_sol2 = pd.DataFrame(data2, columns=['Movie', 'Time Slot', 'Adults Viewership'])
df_s_sol3 = pd.DataFrame(data3, columns=['Movie', 'Time Slot', 'Retirees Viewership'])

# 合并所有的 DataFrame
df_combined = pd.merge(df_s_sol1, df_s_sol2, on=['Movie', 'Time Slot'], how='outer')
df_combined = pd.merge(df_combined, df_s_sol3, on=['Movie', 'Time Slot'], how='outer')

# 保存为 CSV 文件
df_combined.to_csv('viewership_results.csv', index=False)

print("CSV 文件已保存!")

CSV 文件已保存!

In [34]:
# for c in C:
#     for t in T_ad[c]:
#         for m in M:
#             key = (movie_database.loc[m, 'title'], c, t)
#             solution_value = prob.getSolution(z.get(key, 0))
#             print(f"Key: {key}, Solution Value: {solution_value}")
#             if solution_value > 0.001:
#                 z_sol[key] = solution_value

In [35]:
x_sol

{('Harry Potter and the Goblet of Fire', 0): 0.9999999999999996,
 ('Harry Potter and the Goblet of Fire', 1): 0.9999999999999996,
 ('Harry Potter and the Goblet of Fire', 2): 0.9999999999999996,
 ('Harry Potter and the Goblet of Fire', 3): 0.9999999999999996,
 ('Harry Potter and the Goblet of Fire', 4): 0.9999999999999996,
 ('Harry Potter and the Goblet of Fire', 5): 0.9999999999999996,
 ('Titanic', 6): 1.0,
 ('Titanic', 7): 1.0,
 ('Titanic', 8): 1.0,
 ('Titanic', 9): 1.0,
 ('Titanic', 10): 1.0,
 ('Titanic', 11): 1.0,
 ('Titanic', 12): 0.9999999999999997,
 ('Titanic', 13): 1.0,
 ('Forrest Gump', 14): 1.0,
 ('Forrest Gump', 15): 1.0,
 ('Forrest Gump', 16): 1.0,
 ('Forrest Gump', 17): 1.0,
 ('Forrest Gump', 18): 1.0,
 ('Forrest Gump', 19): 1.0,
 ('The Wolf of Wall Street', 20): 1.0,
 ('The Wolf of Wall Street', 21): 1.0,
 ('The Wolf of Wall Street', 22): 1.0,
 ('The Wolf of Wall Street', 23): 1.0,
 ('The Wolf of Wall Street', 24): 1.0,
 ('The Wolf of Wall Street', 25): 1.0,
 ('The Wolf of Wall Street', 26): 1.0,
 ('The Godfather', 27): 1.0,
 ('The Godfather', 28): 1.0,
 ('The Godfather', 29): 1.0,
 ('The Godfather', 30): 1.0,
 ('The Godfather', 31): 1.0,
 ('The Godfather', 32): 1.0,
 ('The Godfather', 33): 1.0}

In [36]:
prob.setObjective(objective2, sense=xp.minimize)
#prob.addConstraint(objective >= target_view_count)  # 保持观众人数的结果
prob.solve()

FICO Xpress v9.4.2, Hyper, solve started 23:46:17, Feb 27, 2025
Heap usage: 19MB (peak 52MB, 5471KB system)
Minimizing MILP myproblem using up to 12 threads and up to 15GB memory, with these control settings:
MAXTIME = 700
OUTPUTLOG = 1
NLPPOSTSOLVE = 1
XSLP_DELETIONCONTROL = 0
XSLP_OBJSENSE = 1
Original problem has:
     26122 rows        22500 cols        43000 elements     22300 entities
Presolved problem has:
      6933 rows         3598 cols        20398 elements      3398 entities
LP relaxation tightened
Presolve finished in 0 seconds
Heap usage: 23MB (peak 52MB, 5471KB system)

Coefficient range                    original                 solved
  Coefficients   [min,max] : [ 1.00e+00,  3.40e+01] / [ 3.13e-02,  1.94e+00]
  RHS and bounds [min,max] : [ 1.00e+00,  3.40e+01] / [ 1.00e+00,  3.40e+01]
  Objective      [min,max] : [ 6.76e+03,  3.52e+06] / [ 8.83e+04,  3.52e+06]
Autoscaling applied standard scaling

Will try to keep branch and bound tree memory usage below 7.8GB
Starting concurrent solve with dual (1 thread) and barrier (11 threads)

              Concurrent-Solve,   0s
            Dual                      Barrier
                               objective   sum inf
                         |  P  1064705.0   .0000000
----- interrupted ------ | ------- optimal --------
Concurrent statistics:
           Dual: 2713 simplex iterations, 0.07s
        Barrier: 19 barrier and 223 simplex iterations, 0.06s
            Barrier used 11 threads 6 cores
            Barrier used AVX2 support, crossover used 1 thread
Optimal solution found

   Its         Obj Value      S   Ninf  Nneg        Sum Inf  Time
     0       1064704.990      P      0     0        .000000     0
Barrier solved problem
  19 barrier and 223 simplex iterations in 0.08 seconds at time 0

Final objective                       : 1.064704990000000e+06
  Max primal violation      (abs/rel) : 1.776e-15 / 1.421e-15
  Max dual violation        (abs/rel) : 1.863e-10 / 1.753e-10
  Max complementarity viol. (abs/rel) :       0.0 /       0.0

Starting root cutting & heuristics
Deterministic mode with up to 1 additional thread

 Its Type    BestSoln    BestBound   Sols    Add    Del     Gap     GInf   Time
R         1966675.440  1064704.990      1                 45.86%       0      0
R         1064704.990  1064704.990      2                 -0.00%       0      0
STOPPING - MIPRELSTOP target reached (MIPRELSTOP=0.0001  gap=-2.18681e-16).
 *** Search completed ***
Uncrunching matrix
Final MIP objective                   : 1.064704990000000e+06
Final MIP bound                       : 1.064704990000000e+06
  Solution time / primaldual integral :      0.62s/ 87.834654%
  Number of solutions found / nodes   :         2 /         1
  Max primal violation      (abs/rel) : 1.776e-15 / 7.105e-17
  Max integer violation     (abs    ) :       0.0

(<SolveStatus.COMPLETED: 3>, <SolStatus.OPTIMAL: 1>)

In [37]:
# # 计算并打印总 License Fee
# total_license_fee = sum(
#     movie_database.loc[m, 'license fee'] * y[movie_database.loc[m, 'title']] for m in M
# )

In [38]:
# prob.setObjective(total_license_fee, sense=xp.minimize)
# prob.solve()

In [39]:
# total_ad_cost = xp.Sum(
#     df_sch_0.loc[t, 'ad_slot_price'] * z[(0, m, t)] 
#     for t in T2[channal_0_time_slots[n-2]:channal_0_time_slots[n-1]]
#     for m in M
# ) + xp.Sum(
#     df_sch_1.loc[t, 'ad_slot_price'] * z[(1, m, t)] 
#     for t in T3[channal_1_time_slots[n-2]:channal_1_time_slots[n-1]]
#     for m in M
# ) + xp.Sum(
#     df_sch_2.loc[t, 'ad_slot_price'] * z[(2, m, t)] 
#     for t in T4[channal_2_time_slots[n-2]:channal_2_time_slots[n-1]]
#     for m in M
# )

In [40]:
# prob.setObjective(total_ad_cost, sense=xp.minimize)
# prob.solve()